[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Le Trung Hai"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
